### ISSUE TITLE
'symlinks'

### ISSUE THREAD

**Issue by Walkman100** [Cito/cito.github.io#2]
Hi Cito, on your [post about windows overlay icons](https://cito.github.io/blog/overlay-icon-battle/) (that python script is very useful thanks), you mention making a symlink to the python executable, but then talk about it's properties as if it were a shortcut (.lnk).

In case you aren't aware, symlinks are completely different from shortcuts - if you're using the term because you're familiar with a Linux environment and that's how you create a 'shortcut' there, windows also supports symlinks but you have to use a third party tool or the command line to create them - completely different from shortcuts, which are a .lnk binary format file only used on Windows.

It would be great if you could change `symlink` to `shortcut`. Minor change I know, and I don't know how popular this page is, but it bugs me :)

I could change it myself and submit a PR, but you'd have to point me to the right file - Surely you don't edit [blog/overlay-icon-battle/index.html](https://github.com/Cito/cito.github.io/blob/master/blog/overlay-icon-battle/index.html) directly...

**Comment by Cito** [comment]
You're right, I changed the wording now. Thank you for the feedback!
